name = "parking-sign-form-maintenance"
main = "./maintenance-worker.mjs"
compatibility_date = "2026-07-08"

[secrets]
required = [
  "GITHUB_TOKEN",
  "GITHUB_REPO_OWNER",
  "GITHUB_REPO_NAME",
  "GITHUB_REPO_BRANCH",
  "GITHUB_CONFIG_PATH",
]
